server:
  port: 9023
#user:
  #urlPath: http://localhost:9021/
spring:
  application:
    name: microservice-customer-movie-ribbon
  cloud:
    config:
      profile: dev
      #uri: http://localhost:8888/ # http://localhost:8088/   microservice-config-server
      label: master
      discovery:
        service-id: microservice-config-server #发现的配置服务名称 建议使用
  #profiles: dev,test,prod  #默认使用 ${spring.application.name}-${profiles}
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true #以ip地址的形式显示
ribbon:   #客户端负载平衡器
  eureka:
    enabled: false #是否在ribbon中禁用eureka
  eager-load: true #饥饿加载：加速springCloud 对服务接口的第一次加载
microservice-privider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #负载均衡:高可用
    listOfServers: http://localhost:9021/ #禁用eureka,配置rubbon能访问的服务节点,多个以“，”隔开
stores:
  ribbon:
    listOfServers: localhost:9021  #允许ribbon加载的url集合
# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000  #请求连接超时时间
        readTimeout: 5000
        loggerLevel: full     #日志级别：basic、none、header、full
