server:
  port: 9023
#user:
  #urlPath: http://localhost:9021/
spring:
  application:
    name: microservice-customer-movie-ribbon
eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true #以ip地址的形式显示
ribbon:   #客户端负载平衡器
  eureka:
    enabled: true #是否在ribbon中禁用eureka
  eager-load: true #饥饿加载：加速springCloud 对服务接口的第一次加载
microservice-privider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #负载均衡:高可用
    listOfServers: http://localhost:9021/ #禁用eureka,配置rubbon能访问的服务节点,多个以“，”隔开
stores:
  ribbon:
    listOfServers: localhost:9021  #允许ribbon加载的url集合
# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: true
  client:
      config:
        default:
          connectTimeout: 5000  #请求连接超时时间
          readTimeout: 5000
          loggerLevel: full     #日志级别：basic、none、header、full
# To set thread isolation to SEMAPHORE 将线程隔离设置为SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
zuul:         #路由器和过滤器配置
  routes:
    users:    #让zuul方向代理微服务，路径是/user/** users只要是唯一的就行，可随意写
      path: /user/**      #url配置
      url: microservice-privider-user  #发现的服务名称
      sensitiveHeaders: Cookie,Set-Cookie,Authorization #设置敏感的标题（现在的值为默认）
      stripPrefix: false #是否携带前缀
  #ignored-services: '*' #除了配置的路由以外其他全部被忽略
endpoints:      #路由端点列表  /routes GET:返回所有映射路由的列表，POST：强制刷新现在的路由列表
  routes:
    enabled: true
management:     #免认证登录
  security:
    enabled: false