
server:
  port: 9023
#user:
  #urlPath: http://localhost:9021/
spring:
  application:
    name: microservice-customer-movie-ribbon
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true #是否在ribbon中禁用eureka
  eager-load: true
microservice-privider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #负载均衡:高可用
    listOfServers: http://localhost:9021/ #禁用eureka,配置rubbon能访问的服务节点,多个以“，”隔开
stores:
  ribbon:
    listOfServers: http://localhost:9021/
