
server:
  port: 9021
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #schema: classpath:schema.sql
    #data: classpath:data.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  application:
    name: microservice-privider-user
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.whl: debug
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}}
    prefer-ip-address: true



