
server:
  port: 9021
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: root
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
    #连接池的配置信息
    ## 初始化大小，最小，最大
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
    ## 配置获取连接等待超时的时间
      maxWait: 60000
    #schema: classpath:schema.sql
    #data: classpath:data.sql
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  application:
    name: miscroservice-privider-user
  cloud:
    config:
      profile: test   #指定获取dev、test、prod文件
      #uri: http://localhost:8888/ # http://localhost:8088/   microservice-config-server
      label: master
      discovery:
        service-id: microservice-config-server #发现的配置服务名称 建议使用
  #profiles: dev,test,prod  #默认使用 ${spring.application.name}-${profiles}
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.whl: debug
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}}
    prefer-ip-address: true



