INSERT INTO TM_USER (USER_NAME,NAME,AGE,BALANCE) VALUES('mackjie','吴豪磊',22,7500.00);
INSERT INTO TM_USER (USER_NAME,NAME,AGE,BALANCE) VALUES('zhangsan','张三',23,7500.00);
INSERT INTO TM_USER (USER_NAME,NAME,AGE,BALANCE) VALUES('lisi','李四',23,7700.00);
INSERT INTO TM_USER (USER_NAME,NAME,AGE,BALANCE) VALUES('wangwu','王五',24,8500.00);
INSERT INTO TM_USER (USER_NAME,NAME,AGE,BALANCE) VALUES('zhaoliu','赵六',25,9500.00);
